name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
