name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-release-draft:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          token: ${{ secrets.GITHUB_TOKEN }}
